name: CI - Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read package.json
        id: package_json
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: package.json

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: myawesomeapps
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Docker Hub access token

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            myawesomeapps/${{fromJson(steps.package_json.outputs.content).name}}:${{fromJson(steps.package_json.outputs.content).version}}
            myawesomeapps/${{fromJson(steps.package_json.outputs.content).name}}:latest
